labels:
  idc: cnc
  service: web
targets:
  - 8.8.8.8
  - 8.8.4.4:
      asn: 151600
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844:
      asn: 151611
  - google.com:
      asn: 15169
dns:
  refresh: 2m15s
  nameserver: 8.8.8.8

ping:
  interval: 5s
  timeout: 3s
  history-size: 42
  payload-size: 120

options:
  disableIPv6: true